# make sure everything is available to the app.
library(shiny)
library(reshape2)
library(popbio)
library(magrittr)
library(tidyverse)
library(cowplot)
library(ggridges)
library(knitr)
library(shinydashboard)
source("compare_det_plots_server.r", local = T)
source("compare_det_plots_server2.r", local = T)
source("compare_det_plotsUI.r", local = T)
source("compare_det_plotsUI2.r", local = T)
source("compare_det_server.r", local = T)
source("compare_detUI.r", local = T)
source("compare_modUI.r", local = T)

source("compare_stoch_plots_server.r", local = T)
source("compare_stoch_plots_server2.r", local = T)
source("compare_stoch_plotsUI.r", local = T)
source("compare_stoch_plotsUI2.r", local = T)
source("compare_stoch_server.r", local = T)
source("compare_stochUI.r", local = T)

source("det_mod_server.r", local = T)
source("det_modUI.r", local = T)

source("server.r", local = T)
source("stoch_modUI.r", local = T)
source("stoch_mod_server.r", local = T)
source("ui.r", local = T)
